name: junitconfiguration
version: 0.5.7
author: Lukas Renggli <renggli@gmail.com>
description: A test configuration producing JUnit compatible output.
homepage: https://github.com/renggli/JUnitConfigurationDart
dependencies:
  meta: '>=0.7.0'
  unittest: '>=0.7.0'
