name: junitconfiguration
version: 0.0.2
author: Lukas Renggli <renggli@gmail.com>
description: A test configuration producing JUnit compatible output.
homepage: https://github.com/renggli/JUnitConfigurationDart
dependencies:
  unittest: '>=0.3.1+1'

#dependencies:
#  unittest: any