name: junitconfiguration
author: Lukas Renggli <renggli@gmail.com>
version: 1.0.3
homepage: https://github.com/renggli/JUnitConfigurationDart
description: A test configuration producing JUnit compatible output.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  unittest: '>=0.9.0 <0.12.0'