name: junitconfiguration
version: 0.5.0
author: Lukas Renggli <renggli@gmail.com>
description: A test configuration producing JUnit compatible output.
homepage: https://github.com/renggli/JUnitConfigurationDart
dependencies:
  unittest: '>=0.5.0'